# Generated by Django 5.0.6 on 2024-05-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='number_of_pages',
            field=models.IntegerField(),
        ),
    ]
